{% set version = "0.17.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-stringfish
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stringfish_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stringfish/stringfish_{{ version }}.tar.gz
  sha256: 9e0af5404b07c2db5912f8663dbb6f09c813b5598d7ec90fd5501f1c4453d674

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'             # [win]
    - '*/Rblas.dll'         # [win]
    - '*/Rlapack.dll'       # [win]
    - '*/RcppParallel.dll'  # [win]
    - '*/tbb.dll'           # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-rcppparallel               # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcppparallel
    - pcre2                        # [not win]
    - tbb                          # [not win]
  run:
    - r-base
    - r-rcpp
    - r-rcppparallel

test:
  commands:
    - $R -e "library('stringfish')"           # [not win]
    - "\"%R%\" -e \"library('stringfish')\""  # [win]

about:
  home: https://github.com/traversc/stringfish
  license: GPL-3.0-only
  summary: Provides an extendable and performant 'alt-string' implementation backed by 'C++' vectors and strings.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
