{% set version = "0.16.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-stringfish
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/stringfish_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/stringfish/stringfish_{{ version }}.tar.gz
  sha256: 3608bc83900246297b38df46954bd9aa3b6f463a56eefbe80cfc713eab797993

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [osx and r_base == "3.6"]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-rcppparallel
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-rcppparallel

test:
  commands:
    - $R -e "library('stringfish')"           # [not win]
    - "\"%R%\" -e \"library('stringfish')\""  # [win]

about:
  home: https://github.com/traversc/stringfish
  license: GPL-3.0-only
  summary: Provides an extendable and performant 'alt-string' implementation backed by 'C++' vectors and strings.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
